### ISSUE TITLE
can we make this a public repo? I cant submodule if it is private

### ISSUE THREAD

**Issue by wheaton5** [thegenemyers/PHASE-MERS#1]
.

**Comment by thegenemyers** [comment]
I'd prefer things that are not fully worked out not be visible to all.
I don't understand what it is you can't do, is it a matter of permissions?
   -- Gene

**Comment by wheaton5** [comment]
I can't git submodule a private repo into a public repo. You could just put in the readme that it is under development and pre-release. Or I can just copy the code directly into my repo instead of pointing at this repo.

**Comment by thegenemyers** [comment]
OK, I made it public -- it is code built for you. (But I could ask you 
why your repo is public
given it isn't ready for release and is a research project still 
underway :-).  I personally don't
like making things public until they are really ready to be public.
   -- Gene

**Comment by wheaton5** [comment]
thanks
